version: "3.8"

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
      build: .
      ports:
        - 8080:8080
      environment:
        APP_NAME: DistanceClaculator
        PORT: 8080
        DB_URI: mongodb://mongo_db:27017/distancecalculator
      depends_on:
        - mongo_db

volumes:
  mongo_db: {}